services:
  bot:
    build: .
    volumes:
      - ./prisma/dev.db:/app/data/db/dev.db
    environment:
      PORT: "3000"
      LOG_LEVEL: "DEBUG"
      DISCORD_TOKEN: "MTMyMDg3NjcyODEyNTYyMDMxOA.GsSMqg.xVctk-fxE1IGsKfu96ZivPGPNPowsd5f55zhAw"
      DISCORD_DEVELOPMENT_GUILD_ID: "137229336037163008"
